// import { Inter } from 'next/font/google'
 import './globals.scss'
import Header from "components/Header"
import Side from "components/side"
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'News App',

  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
       
      </head>
      <body>
      <div >
         {/* <Side  /> */}
         <div className='Headbar'>
            <Header />
            <div>
          {children}
          </div>
          </div>
          
      </div>
 

      </body>

      
      
    </html>
  )
}
